### ISSUE TITLE
Question about Evaluation Script

### ISSUE THREAD

**Issue by zytzrh** [luwei0917/TankBind#14]
Thanks for your awesome work!

I try to reproduce the results reported in paper using the checkpoint `self-dock.pt`. But the results seem different. And even in a more simple setting where I have already known the true binding site (which is 20A radius around true compound center), the results show difference. 

I follow the evaluation paradigm as I first predict distance map and then use this distance map for 5000 epoch's gradient descent. But my result shows that I only get 20% test data whithin 5A threshold. Do I make some mistakes?

I would appreciate it very much if you could provide the evaluation script!

**Comment by luwei0917** [comment]
you could use the true binding center instead of the p2rank predicted center, but don't change the block radius, since the model is trained with the default size. Are you following the same steps as listed in https://github.com/luwei0917/TankBind/blob/main/examples/prediction_example_using_PDB_6hd6.ipynb ?  I don't think you need change any setting. my evaluation script simply does the same in a batch mode.

**Comment by zytzrh** [comment]
I find the problem. It should be that when I use `Chem.MolFromMolFile(sdf_fileName, sanitize=False, removeHs=True)`. The rdkit mol returned still contain the hydrogen atoms. So it make the model perform worse and the evaluation not accurate. 

By the way, thanks for your suggestions!
